spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supbio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    usePool: true
    timeout: 3000
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
swagger:
  show: true
