spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supbio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    usePool: true
    timeout: 3000
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
swagger:
  show: true
pay:
  weChat:
    appSecret: 8ef5787dee3fd7a4eb802fc13632f8a1 #应用密钥
    appId: wx6e12223a6bd82ca9 #应用APPID
    mchId: #微信支付分配的商户号
    body: 蟠桃医生-购买服务 #商品描述
    notifyUrl: http://localhost:8080/api/app/weChatPay/notifyCallback #微信支付异步通知回调地址
    tradeType: APP
    unifiedOrder: https://api.mch.weixin.qq.com/pay/unifiedorder #微信统一下单接口路径
